Implemented Authentication
PSBicep/BicepNet pull request #49
Opened 2022-09-27 14:28 UTC by PalmEmanuel

Solves #33 by adding new commands and full support for custom authentication. Removes our soft dependency on the Az CLI and the Az PowerShell Module, but keeps the functionality the same if they're available.

Strongly related to https://github.com/PSBicep/PSBicep/issues/258.

New commands:
- `Set-BicepNetCredential` - Sets a credential for the current PowerShell session.
  - Without parameters or with `-TenantId` - Allows the user to interactively log in through the browser.
  - With `-AccessToken` - Allows the user to provide an existing token for authentication
- `Clear-BicepNetCredential` - Removes the credential set by `Set-BicepNetCredential`.
- `Get-BicepNetAccessToken` - Gets the access token from the credential set by `Set-BicepNetCredential`

Still missing some verbosity and logging but I thought I'd open the PR, suggestions or additions appreciated!

2022-10-15 11:02 UTC, SimonWahlin requested changes
Have a few comments, oterwise it looks good!

2022-10-15 11:02 UTC, SimonWahlin commented on BicepNet.Core/BicepWrapper.cs
> +    public static void SetAuthentication(string? token = null, string? tenantId = null)
I think we should put all auth logic in BicepWrapper.Authentication.cs

2022-10-23 16:51 UTC, PalmEmanuel commented on BicepNet.Core/BicepWrapper.cs
> +    public static void SetAuthentication(string? token = null, string? tenantId = null)
Good call, I had trouble writing it in a way I found clean before. Pushed some changes that look much better to me, lemme know what you think!

2022-10-29 20:25 UTC, SimonWahlin requested changes
Looks good!
Will you fix the merge conflict so we can merge?

2022-10-29 20:34 UTC, SimonWahlin approved these changes

2022-10-29 20:36 UTC, merged